
package com.c_s_center.webserviceinvoce;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceC_S_Center", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", wsdlLocation = "http://localhost:8080/Criminal_security/WebServiceC_S_Center?wsdl")
public class WebServiceCSCenter_Service
    extends Service
{

    private final static URL WEBSERVICECSCENTER_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECSCENTER_EXCEPTION;
    private final static QName WEBSERVICECSCENTER_QNAME = new QName("http://webServiceInvoce.C_S_Center.com/", "WebServiceC_S_Center");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Criminal_security/WebServiceC_S_Center?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECSCENTER_WSDL_LOCATION = url;
        WEBSERVICECSCENTER_EXCEPTION = e;
    }

    public WebServiceCSCenter_Service() {
        super(__getWsdlLocation(), WEBSERVICECSCENTER_QNAME);
    }

    public WebServiceCSCenter_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECSCENTER_QNAME, features);
    }

    public WebServiceCSCenter_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECSCENTER_QNAME);
    }

    public WebServiceCSCenter_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECSCENTER_QNAME, features);
    }

    public WebServiceCSCenter_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCSCenter_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCSCenter
     */
    @WebEndpoint(name = "WebServiceC_S_CenterPort")
    public WebServiceCSCenter getWebServiceCSCenterPort() {
        return super.getPort(new QName("http://webServiceInvoce.C_S_Center.com/", "WebServiceC_S_CenterPort"), WebServiceCSCenter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCSCenter
     */
    @WebEndpoint(name = "WebServiceC_S_CenterPort")
    public WebServiceCSCenter getWebServiceCSCenterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServiceInvoce.C_S_Center.com/", "WebServiceC_S_CenterPort"), WebServiceCSCenter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECSCENTER_EXCEPTION!= null) {
            throw WEBSERVICECSCENTER_EXCEPTION;
        }
        return WEBSERVICECSCENTER_WSDL_LOCATION;
    }

}
