
package com.c_s_center.webserviceinvoce;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceC_S_Center", targetNamespace = "http://webServiceInvoce.C_S_Center.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceCSCenter {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addcs", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.Addcs")
    @ResponseWrapper(localName = "addcsResponse", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.AddcsResponse")
    @Action(input = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/addcsRequest", output = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/addcsResponse")
    public String addcs(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletecs", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.Deletecs")
    @ResponseWrapper(localName = "deletecsResponse", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.DeletecsResponse")
    @Action(input = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/deletecsRequest", output = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/deletecsResponse")
    public void deletecs(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     */
    @WebMethod
    @RequestWrapper(localName = "updatecs", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.Updatecs")
    @ResponseWrapper(localName = "updatecsResponse", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.UpdatecsResponse")
    @Action(input = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/updatecsRequest", output = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/updatecsResponse")
    public void updatecs(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcsList", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.GetcsList")
    @ResponseWrapper(localName = "getcsListResponse", targetNamespace = "http://webServiceInvoce.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce.GetcsListResponse")
    @Action(input = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/getcsListRequest", output = "http://webServiceInvoce.C_S_Center.com/WebServiceC_S_Center/getcsListResponse")
    public String getcsList();

}
