
package com.c_s_center.webserviceinvoce1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceC_S_Center1", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceCSCenter1 {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addcitizen", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.Addcitizen")
    @ResponseWrapper(localName = "addcitizenResponse", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.AddcitizenResponse")
    @Action(input = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/addcitizenRequest", output = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/addcitizenResponse")
    public String addcitizen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletecitizen", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.Deletecitizen")
    @ResponseWrapper(localName = "deletecitizenResponse", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.DeletecitizenResponse")
    @Action(input = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/deletecitizenRequest", output = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/deletecitizenResponse")
    public void deletecitizen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "updatecitizen", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.Updatecitizen")
    @ResponseWrapper(localName = "updatecitizenResponse", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.UpdatecitizenResponse")
    @Action(input = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/updatecitizenRequest", output = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/updatecitizenResponse")
    public void updatecitizen(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcitizenList", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.GetcitizenList")
    @ResponseWrapper(localName = "getcitizenListResponse", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", className = "com.c_s_center.webserviceinvoce1.GetcitizenListResponse")
    @Action(input = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/getcitizenListRequest", output = "http://webServiceInvoce1.C_S_Center.com/WebServiceC_S_Center1/getcitizenListResponse")
    public String getcitizenList();

}
