
package com.c_s_center.webserviceinvoce1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceC_S_Center1", targetNamespace = "http://webServiceInvoce1.C_S_Center.com/", wsdlLocation = "http://localhost:8080/Civil_Affairs/WebServiceC_S_Center1?wsdl")
public class WebServiceCSCenter1_Service
    extends Service
{

    private final static URL WEBSERVICECSCENTER1_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECSCENTER1_EXCEPTION;
    private final static QName WEBSERVICECSCENTER1_QNAME = new QName("http://webServiceInvoce1.C_S_Center.com/", "WebServiceC_S_Center1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Civil_Affairs/WebServiceC_S_Center1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECSCENTER1_WSDL_LOCATION = url;
        WEBSERVICECSCENTER1_EXCEPTION = e;
    }

    public WebServiceCSCenter1_Service() {
        super(__getWsdlLocation(), WEBSERVICECSCENTER1_QNAME);
    }

    public WebServiceCSCenter1_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECSCENTER1_QNAME, features);
    }

    public WebServiceCSCenter1_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECSCENTER1_QNAME);
    }

    public WebServiceCSCenter1_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECSCENTER1_QNAME, features);
    }

    public WebServiceCSCenter1_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCSCenter1_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCSCenter1
     */
    @WebEndpoint(name = "WebServiceC_S_Center1Port")
    public WebServiceCSCenter1 getWebServiceCSCenter1Port() {
        return super.getPort(new QName("http://webServiceInvoce1.C_S_Center.com/", "WebServiceC_S_Center1Port"), WebServiceCSCenter1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCSCenter1
     */
    @WebEndpoint(name = "WebServiceC_S_Center1Port")
    public WebServiceCSCenter1 getWebServiceCSCenter1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServiceInvoce1.C_S_Center.com/", "WebServiceC_S_Center1Port"), WebServiceCSCenter1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECSCENTER1_EXCEPTION!= null) {
            throw WEBSERVICECSCENTER1_EXCEPTION;
        }
        return WEBSERVICECSCENTER1_WSDL_LOCATION;
    }

}
